//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Act6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CarPrices = new HashSet<CarPrice>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> ProvinceID { get; set; }
    
        public virtual ICollection<CarPrice> CarPrices { get; set; }
        public virtual Province Province { get; set; }
        public virtual OnlineSale OnlineSale { get; set; }
        public virtual OnsiteSale OnsiteSale { get; set; }
    }
}
